management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: messenger
  kafka:
    bootstrap-servers:
      - localhost:9092
  boot:
    admin:
      client:
        url: http://localhost:9090